# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/roamer/extract-files.sh - DO NOT EDIT

# All the blobs necessary for roamer
PRODUCT_COPY_FILES += \
    vendor/zte/roamer/proprietary/dhd.ko:system/lib/dhd.ko \
    #vendor/zte/roamer/proprietary/regcode:system/wifi/regcode \
    #vendor/zte/roamer/proprietary/data.patch.hw2_0.bin:system/wifi/data.patch.hw2_0.bin \
    #vendor/zte/roamer/proprietary/athwlan.bin.z77:system/wifi/athwlan.bin.z77 \
    #vendor/zte/roamer/proprietary/athtcmd_ram.bin:system/wifi/athtcmd_ram.bin \
    vendor/zte/roamer/proprietary/libaudio.so:system/lib/libaudio.so \
    vendor/zte/roamer/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/zte/roamer/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/zte/roamer/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/zte/roamer/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/zte/roamer/proprietary/libgsl.so:system/lib//libgsl.so \
    vendor/zte/roamer/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/zte/roamer/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/zte/roamer/proprietary/qmuxd:system/bin/qmuxd \
    vendor/zte/roamer/proprietary/akmd2:system/bin/akmd2 \
    vendor/zte/roamer/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/zte/roamer/proprietary/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/zte/roamer/proprietary/libdiag.so:system/lib/libdiag.so \
    vendor/zte/roamer/proprietary/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    vendor/zte/roamer/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/zte/roamer/proprietary/libqmi.so:system/lib/libqmi.so \
    vendor/zte/roamer/proprietary/libdsm.so:system/lib/libdsm.so \
    vendor/zte/roamer/proprietary/libqueue.so:system/lib/libqueue.so \
    vendor/zte/roamer/proprietary/libdll.so:system/lib/libdll.so \
    vendor/zte/roamer/proprietary/libcm.so:system/lib/libcm.so \
    vendor/zte/roamer/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/zte/roamer/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/zte/roamer/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/zte/roamer/proprietary/libwms.so:system/lib/libwms.so \
    vendor/zte/roamer/proprietary/libnv.so:system/lib/libnv.so \
    vendor/zte/roamer/proprietary/libwmsts.so:system/lib/libwmsts.so \
    vendor/zte/roamer/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/zte/roamer/proprietary/libdss.so:system/lib/libdss.so \
    vendor/zte/roamer/proprietary/libauth.so:system/lib/libauth.so \
    vendor/zte/roamer/proprietary/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/zte/roamer/proprietary/lights.msm7k.so:system/lib/hw/lights.msm7k.so \
    vendor/zte/roamer/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/zte/roamer/proprietary/liboemcamera.so:obj/lib/liboemcamera.so \
    vendor/zte/roamer/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/zte/roamer/proprietary/libmmipl.so:system/lib/libmmipl.so \
    vendor/zte/roamer/proprietary/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/zte/roamer/proprietary/libOmxEvrcEnc.so:/system/lib/libOmxEvrcEnc.so \
    vendor/zte/roamer/proprietary/libOmxAacDec.so:/system/lib/libOmxAacDec.so \
    vendor/zte/roamer/proprietary/libOmxWmvDec.so:/system/lib/libOmxWmvDec.so \
    vendor/zte/roamer/proprietary/libOmxQcelpDec.so:/system/lib/libOmxQcelpDec.so \
    vendor/zte/roamer/proprietary/libOmxAmrEnc.so:/system/lib/libOmxAmrEnc.so \
    vendor/zte/roamer/proprietary/libOmxAdpcmDec.so:/system/lib/libOmxAdpcmDec.so \
    vendor/zte/roamer/proprietary/libOmxEvrcDec.so:/system/lib/libOmxEvrcDec.so \
    vendor/zte/roamer/proprietary/libOmxH264Dec.so:/system/lib/libOmxH264Dec.so \
    vendor/zte/roamer/proprietary/libOmxAmrDec.so:/system/lib/libOmxAmrDec.so \
    vendor/zte/roamer/proprietary/libOmxAmrwbDec.so:/system/lib/libOmxAmrwbDec.so \
    vendor/zte/roamer/proprietary/libOmxWmaDec.so:/system/lib/libOmxWmaDec.so \
    vendor/zte/roamer/proprietary/libOmxQcelp13Enc.so:/system/lib/libOmxQcelp13Enc.so \
    vendor/zte/roamer/proprietary/libOmxMp3Dec.so:/system/lib/libOmxMp3Dec.so \
    vendor/zte/roamer/proprietary/libOmxMpeg4Dec.so:/system/lib/libOmxMpeg4Dec.so \
    vendor/zte/roamer/proprietary/libOmxVidEnc.so:/system/lib/libOmxVidEnc.so \
    vendor/zte/roamer/proprietary/libOmxAmrRtpDec.so:/system/lib/libOmxAmrRtpDec.so \
    vendor/zte/roamer/proprietary/libOmxAacEnc.so:/system/lib/libOmxAacEnc.so \
    vendor/zte/roamer/proprietary/libmm-adspsvc.so:/system/lib/libmm-adspsvc.so \
    vendor/zte/roamer/proprietary/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/zte/roamer/proprietary/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/zte/roamer/proprietary/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/zte/roamer/proprietary/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/zte/roamer/proprietary/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/zte/roamer/proprietary/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/zte/roamer/proprietary/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so



